import time
import google.generativeai as genai
from config import GOOGLE_API_KEY
from get_weather import get_Weather
from datetime import datetime, timezone, timedelta


def unix_to_local_time(unix_timestamp, timezone_offset_seconds):
    """
    Converts a Unix timestamp to a human-readable local time string.

    Parameters:
    - unix_timestamp (int): The Unix timestamp (seconds since Jan 1, 1970 UTC).
    - timezone_offset_seconds (int): The timezone offset in seconds (e.g., +3600 for UTC+1).

    Returns:
    - str: Local time formatted as "HH:MM AM/PM".

    Example:
        unix_timestamp = 1754832000  # corresponds to 2025-08-10 12:00:00 UTC
        timezone_offset_seconds = 7200  # +2 hours offset

        local_time = unix_to_local_time(unix_timestamp, timezone_offset_seconds)
        print(local_time)  # Output: "02:00 PM"
    """

    local_time = datetime.utcfromtimestamp(unix_timestamp) + timedelta(seconds=timezone_offset_seconds)
    return local_time.strftime("%I:%M %p")



_cache = {}
CACHE_DURATION = 15 * 60  

def generate_weather_report(city):
    """
    Generates a weather report for a given city, using cached data if available and recent.

    Parameters:
    - city (str): Name of the city to get the weather for.

    Returns:
    - str: A narrative weather report with practical advice, generated by an AI model.

    How it works:
    1. Normalizes the city name to lowercase and trims spaces.
    2. Checks if the report for this city is cached and not older than CACHE_DURATION seconds.
    3. If cached and fresh, returns the cached report.
    4. Otherwise, calls the weather API to get current data.
    5. Converts sunrise and sunset times from Unix timestamps to local time strings.
    6. Builds a prompt with weather data for the AI to generate a narrative report.
    7. Caches the generated report for future use.
    8. Returns the AI-generated weather report.
    """

    city_key = city.strip().lower()
    current_time = time.time()

    if city_key in _cache:
        cached_time, cached_response = _cache[city_key]
        if current_time - cached_time < CACHE_DURATION:
            return cached_response

    genai.configure(api_key=GOOGLE_API_KEY)

    data = get_Weather(city)

    if not data or "name" not in data:
        return " City not found. Please check the name and try again."

    template = """
Here is the weather data for the city of {city}:
- Current temperature: {temp}°C
- Feels like: {feels_like}°C
- Minimum temperature: {temp_min}°C
- Maximum temperature: {temp_max}°C
- Pressure: {pressure} hPa
- Humidity: {humidity}%
- Weather description: {description}
- Wind speed: {wind_speed} m/s
- Cloud coverage: {clouds}%
- Sunrise time: {sunrise}
- Sunset time: {sunset}

Could you please write a clear and pleasant narrative weather report in the style of a weather news broadcast?

Also, please provide practical advice on suitable clothing and activities.

Report:
"""

    timezone_offset = data.get("timezone", 0)

    params = {
        "city": data["name"],
        "description": data["weather"][0]["description"],
        "temp": data["main"]["temp"],
        "feels_like": data["main"]["feels_like"],
        "temp_min": data["main"]["temp_min"],
        "temp_max": data["main"]["temp_max"],
        "pressure": data["main"]["pressure"],
        "humidity": data["main"]["humidity"],
        "wind_speed": data["wind"]["speed"],
        "clouds": data["clouds"]["all"],
        "sunrise": unix_to_local_time(data["sys"]["sunrise"], timezone_offset),
        "sunset": unix_to_local_time(data["sys"]["sunset"], timezone_offset)
    }

    prompt = template.format(**params)

    model = genai.GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(prompt)

    _cache[city_key] = (current_time, response.text)

    return response.text
