import google.generativeai as genai
from config import GOOGLE_API_KEY
from get_weather import get_Weather
import redis
from cache import r, CACHE_DURATION
from utils import unix_to_local_time





def generate_weather_report(city):
    """
    Generates a weather report for a given city, using cached data if available and recent.

    Parameters:
    - city (str): Name of the city to get the weather for.

    Returns:
    - str: A narrative weather report with practical advice, generated by an AI model.

    How it works:
    1. Normalizes the city name to lowercase and trims spaces.
    2. Checks if the report for this city is cached and not older than CACHE_DURATION seconds.
    3. If cached and fresh, returns the cached report.
    4. Otherwise, calls the weather API to get current data.
    5. Converts sunrise and sunset times from Unix timestamps to local time strings.
    6. Builds a prompt with weather data for the AI to generate a narrative report.
    7. Caches the generated report for future use.
    8. Returns the AI-generated weather report.
    """

    city_key = city.strip().lower()
     
    cached_response = r.get(city_key)
    if cached_response:
        return cached_response.decode()


    genai.configure(api_key=GOOGLE_API_KEY)

    data = get_Weather(city)

    if not data or "name" not in data:
        return " City not found. Please check the name and try again."

    template = """
Here is the weather data for the city of {city}:
- Current temperature: {temp}°C
- Feels like: {feels_like}°C
- Minimum temperature: {temp_min}°C
- Maximum temperature: {temp_max}°C
- Pressure: {pressure} hPa
- Humidity: {humidity}%
- Weather description: {description}
- Wind speed: {wind_speed} m/s
- Cloud coverage: {clouds}%
- Sunrise time: {sunrise}
- Sunset time: {sunset}

Could you please write a clear and pleasant narrative weather report in the style of a weather news broadcast?

Also, please provide practical advice on suitable clothing and activities.

Report:
"""

    timezone_offset = data.get("timezone", 0)

    params = {
        "city": data["name"],
        "description": data["weather"][0]["description"],
        "temp": data["main"]["temp"],
        "feels_like": data["main"]["feels_like"],
        "temp_min": data["main"]["temp_min"],
        "temp_max": data["main"]["temp_max"],
        "pressure": data["main"]["pressure"],
        "humidity": data["main"]["humidity"],
        "wind_speed": data["wind"]["speed"],
        "clouds": data["clouds"]["all"],
        "sunrise": unix_to_local_time(data["sys"]["sunrise"], timezone_offset),
        "sunset": unix_to_local_time(data["sys"]["sunset"], timezone_offset)
    }

    prompt = template.format(**params)

    model = genai.GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(prompt)

    r.setex(city_key, CACHE_DURATION, response.text)

    return response.text
